### ISSUE TITLE
Data round for GNNs using regression

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/3D-Vac#125]
Referring to data description in #113, we want to run the same experiments run for classification task, but using regression as in MHCFlurry 2.0. Report then here the main results and comparisons (maybe also with classification ones?).

- [ ] Add/edit scripts for regression
- [ ] Experiments of issue #124 (standardization)
- [ ] Experiments of issue #127 (batch_size)
- [ ] Experiments of issue #126 (weighted loss function)
- [ ] Experiments of issue #134 (clusters)
